import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from './AuthContext';

type Language = 'es' | 'en';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const translations = {
  es: {
    home: 'Inicio',
    about: 'Nosotros',
    calculator: 'Calculadora',
    contacts: 'Contactos',
    materials: 'Materiales',
    login: 'Ingresar',
    register: 'Registro',
    logout: 'Salir',
    profile: 'Perfil',
    email: 'Correo',
    password: 'Contraseña',
    fullName: 'Nombre Completo',
    phone: 'Teléfono',
    forgotPassword: '¿Olvidaste tu contraseña?',
    resetPassword: 'Restablecer',
    signIn: 'Ingresar',
    signUp: 'Registrarse',
    alreadyHaveAccount: '¿Ya tienes cuenta?',
    dontHaveAccount: '¿No tienes cuenta?',
    welcome: 'Bienvenido',
    welcomeBack: 'Bienvenido',
    createAccount: 'Crear Cuenta',
    sendResetLink: 'Enviar',
    resetLinkSent: 'Enlace enviado a tu correo',
    settings: 'Configuración',
    save: 'Guardar',
    cancel: 'Cancelar',
    updateProfile: 'Actualizar Perfil',
    language: 'Idioma',
    spanish: 'Español',
    english: 'Inglés',
    heroTitle: 'Construimos la Civilización',
    heroSubtitle: 'Expertos en construcción residencial y comercial con más de 20 años de experiencia',
    getStarted: 'Comenzar',
    ourServices: 'Nuestros Servicios',
    residentialConstruction: 'Construcción Residencial',
    commercialConstruction: 'Construcción Comercial',
    renovation: 'Renovación',
    consulting: 'Consultoría',
    aboutTitle: 'Sobre Nosotros',
    aboutDescription: 'Somos una empresa líder en construcción en República Dominicana, dedicada a crear espacios excepcionales.',
    calculatorTitle: 'Calculadora',
    calculatorDescription: 'Calcula el costo estimado de tu proyecto',
    area: 'Área (m²)',
    projectType: 'Tipo de Proyecto',
    residential: 'Residencial',
    commercial: 'Comercial',
    calculate: 'Calcular',
    estimatedCost: 'Costo Estimado',
    contactTitle: 'Contáctanos',
    contactDescription: 'Estamos aquí para ayudarte',
    address: 'Dirección',
    addressValue: 'Santo Domingo, RD',
    phoneValue: '+1 (809) 555-0123',
    emailValue: 'info@civion.do',
    materialsTitle: 'Materiales',
    materialsDescription: 'Los mejores materiales del mercado',
    concrete: 'Concreto',
    steel: 'Acero',
    wood: 'Madera',
    ceramics: 'Cerámica',
    paint: 'Pintura',
    electrical: 'Eléctricos',
    myProjects: 'Mis Proyectos',
    dashboard: 'Dashboard',
    saveProject: 'Guardar Proyecto',
    projectName: 'Nombre del Proyecto',
    projectSaved: 'Proyecto guardado',
    baseCost: 'Costo Base',
    materialsCost: 'Materiales',
    totalCost: 'Total',
    selectMaterials: 'Seleccionar Materiales',
    addMaterial: 'Agregar',
    category: 'Categoría',
    price: 'Precio',
    quantity: 'Cantidad',
    users: 'Usuarios',
    analytics: 'Analíticas',
    assignRole: 'Asignar Rol',
    owner: 'Propietario',
    admin: 'Admin',
    materialsManager: 'Gerente',
    regular: 'Regular',
    pageVisits: 'Visitas',
    calculatorUsage: 'Uso Calculadora',
    contactFormUsage: 'Formularios',
    projectsCreated: 'Proyectos',
    userManagement: 'Usuarios',
    materialsManagement: 'Materiales',
    addCategory: 'Nueva Categoría',
    editMaterial: 'Editar',
    deleteMaterial: 'Eliminar',
    storePrice: 'Precio Tienda',
    companyProfitPrice: 'Con Beneficio',
    discountPrice: 'Con Descuento',
    laborPrice: 'Mano de Obra',
    finalPrice: 'Precio Final',
    unit: 'Unidad',
    isBaseMaterial: 'Base',
    uploadPhoto: 'Subir Foto',
    description: 'Descripción',
    notes: 'Notas',
    createdAt: 'Creado',
    updatedAt: 'Actualizado',
    actions: 'Acciones',
    edit: 'Editar',
    delete: 'Eliminar',
    view: 'Ver',
    back: 'Volver',
    next: 'Siguiente',
    previous: 'Anterior',
    search: 'Buscar',
    filter: 'Filtrar',
    export: 'Exportar',
    import: 'Importar',
    loading: 'Cargando...',
    noData: 'Sin datos',
    error: 'Error',
    success: 'Éxito',
    confirmDelete: '¿Eliminar?',
    yes: 'Sí',
    no: 'No',
    totalVisits: 'Visitas Totales',
    calculatorUses: 'Usos Calculadora',
    contactForms: 'Formularios Contacto',
    totalUsers: 'Total Usuarios',
    activityOverview: 'Vista General',
    chartComingSoon: 'Gráfico próximamente',
    dashboardDescription: 'Vista general de actividad del sitio',
    accessDenied: 'Acceso Denegado',
    noPermission: 'No tienes permiso para ver esta página',
    ownerOnly: 'Solo el propietario puede ver esta página',
    manageUsersAndRoles: 'Gestiona usuarios y sus roles',
    searchUsers: 'Buscar usuarios',
    user: 'Usuario',
    roles: 'Roles',
    joined: 'Registro',
    manageRoles: 'Gestionar Roles',
    managingRolesFor: 'Gestionando roles para',
    remove: 'Quitar',
    assign: 'Asignar',
    close: 'Cerrar',
    materials_manager: 'Gerente Materiales',
    errorAssigningRole: 'Error asignando rol',
    errorRemovingRole: 'Error removiendo rol',
    basicCalculation: 'Cálculo Básico',
    costBreakdown: 'Desglose de Costos',
    done: 'Listo',
    pleaseEnterProjectName: 'Por favor ingrese el nombre del proyecto',
    errorSavingProject: 'Error guardando proyecto',
    loginRequired: 'Inicio de sesión requerido',
    pleaseLoginToViewProjects: 'Por favor inicie sesión para ver proyectos',
    viewYourSavedCalculations: 'Ver tus cálculos guardados',
    noProjects: 'Sin proyectos',
    startByCreatingCalculation: 'Comienza creando un cálculo en la calculadora',
    projectDetails: 'Detalles del Proyecto',
    confirmDeleteProject: '¿Eliminar este proyecto?',
    errorDeletingProject: 'Error eliminando proyecto',
    selectedMaterials: 'Materiales Seleccionados',
    manageMaterialsAndPrices: 'Gestiona materiales y precios',
    newCategory: 'Nueva Categoría',
    newMaterial: 'Nuevo Material',
    searchMaterials: 'Buscar materiales',
    allCategories: 'Todas las categorías',
    active: 'Activo',
    inactive: 'Inactivo',
    baseMaterial: 'Material Base',
    noMaterials: 'Sin materiales',
    startByAddingMaterial: 'Comienza agregando un material',
    editCategory: 'Editar Categoría',
    nameSpanish: 'Nombre (Español)',
    nameEnglish: 'Nombre (Inglés)',
    descriptionSpanish: 'Descripción (Español)',
    descriptionEnglish: 'Descripción (Inglés)',
    photoUrl: 'URL de Foto',
    photo: 'Foto',
    errorSavingMaterial: 'Error guardando material',
    errorDeletingMaterial: 'Error eliminando material',
    errorSavingCategory: 'Error guardando categoría',
    errorDeletingCategory: 'Error eliminando categoría',
    categories: 'Categorías',
  },
  en: {
    home: 'Home',
    about: 'About',
    calculator: 'Calculator',
    contacts: 'Contacts',
    materials: 'Materials',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    profile: 'Profile',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    phone: 'Phone',
    forgotPassword: 'Forgot password?',
    resetPassword: 'Reset',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    alreadyHaveAccount: 'Have account?',
    dontHaveAccount: "No account?",
    welcome: 'Welcome',
    welcomeBack: 'Welcome back',
    createAccount: 'Create Account',
    sendResetLink: 'Send',
    resetLinkSent: 'Link sent to email',
    settings: 'Settings',
    save: 'Save',
    cancel: 'Cancel',
    updateProfile: 'Update Profile',
    language: 'Language',
    spanish: 'Spanish',
    english: 'English',
    heroTitle: 'We Build Civilization',
    heroSubtitle: 'Experts in residential and commercial construction with over 20 years of experience',
    getStarted: 'Get Started',
    ourServices: 'Our Services',
    residentialConstruction: 'Residential',
    commercialConstruction: 'Commercial',
    renovation: 'Renovation',
    consulting: 'Consulting',
    aboutTitle: 'About Us',
    aboutDescription: 'We are a leading construction company in Dominican Republic, creating exceptional spaces.',
    calculatorTitle: 'Calculator',
    calculatorDescription: 'Calculate project cost',
    area: 'Area (m²)',
    projectType: 'Project Type',
    residential: 'Residential',
    commercial: 'Commercial',
    calculate: 'Calculate',
    estimatedCost: 'Estimated Cost',
    contactTitle: 'Contact Us',
    contactDescription: 'We are here to help',
    address: 'Address',
    addressValue: 'Santo Domingo, DR',
    phoneValue: '+1 (809) 555-0123',
    emailValue: 'info@civion.do',
    materialsTitle: 'Materials',
    materialsDescription: 'Best market materials',
    concrete: 'Concrete',
    steel: 'Steel',
    wood: 'Wood',
    ceramics: 'Ceramics',
    paint: 'Paint',
    electrical: 'Electrical',
    myProjects: 'My Projects',
    dashboard: 'Dashboard',
    saveProject: 'Save Project',
    projectName: 'Project Name',
    projectSaved: 'Project saved',
    baseCost: 'Base Cost',
    materialsCost: 'Materials',
    totalCost: 'Total',
    selectMaterials: 'Select Materials',
    addMaterial: 'Add',
    category: 'Category',
    price: 'Price',
    quantity: 'Quantity',
    users: 'Users',
    analytics: 'Analytics',
    assignRole: 'Assign Role',
    owner: 'Owner',
    admin: 'Admin',
    materialsManager: 'Manager',
    regular: 'Regular',
    pageVisits: 'Visits',
    calculatorUsage: 'Calculator',
    contactFormUsage: 'Forms',
    projectsCreated: 'Projects',
    userManagement: 'Users',
    materialsManagement: 'Materials',
    addCategory: 'New Category',
    editMaterial: 'Edit',
    deleteMaterial: 'Delete',
    storePrice: 'Store Price',
    companyProfitPrice: 'W/ Profit',
    discountPrice: 'W/ Discount',
    laborPrice: 'Labor',
    finalPrice: 'Final Price',
    unit: 'Unit',
    isBaseMaterial: 'Base',
    uploadPhoto: 'Upload Photo',
    description: 'Description',
    notes: 'Notes',
    createdAt: 'Created',
    updatedAt: 'Updated',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    loading: 'Loading...',
    noData: 'No data',
    error: 'Error',
    success: 'Success',
    confirmDelete: 'Delete?',
    yes: 'Yes',
    no: 'No',
    totalVisits: 'Total Visits',
    calculatorUses: 'Calculator Uses',
    contactForms: 'Contact Forms',
    totalUsers: 'Total Users',
    activityOverview: 'Activity Overview',
    chartComingSoon: 'Chart coming soon',
    dashboardDescription: 'Site activity overview',
    accessDenied: 'Access Denied',
    noPermission: 'You do not have permission to view this page',
    ownerOnly: 'Only the owner can view this page',
    manageUsersAndRoles: 'Manage users and their roles',
    searchUsers: 'Search users',
    user: 'User',
    roles: 'Roles',
    joined: 'Joined',
    manageRoles: 'Manage Roles',
    managingRolesFor: 'Managing roles for',
    remove: 'Remove',
    assign: 'Assign',
    close: 'Close',
    materials_manager: 'Materials Manager',
    errorAssigningRole: 'Error assigning role',
    errorRemovingRole: 'Error removing role',
    basicCalculation: 'Basic Calculation',
    costBreakdown: 'Cost Breakdown',
    done: 'Done',
    pleaseEnterProjectName: 'Please enter project name',
    errorSavingProject: 'Error saving project',
    loginRequired: 'Login Required',
    pleaseLoginToViewProjects: 'Please login to view projects',
    viewYourSavedCalculations: 'View your saved calculations',
    noProjects: 'No projects',
    startByCreatingCalculation: 'Start by creating a calculation',
    projectDetails: 'Project Details',
    confirmDeleteProject: 'Delete this project?',
    errorDeletingProject: 'Error deleting project',
    selectedMaterials: 'Selected Materials',
    manageMaterialsAndPrices: 'Manage materials and prices',
    newCategory: 'New Category',
    newMaterial: 'New Material',
    searchMaterials: 'Search materials',
    allCategories: 'All categories',
    active: 'Active',
    inactive: 'Inactive',
    baseMaterial: 'Base Material',
    noMaterials: 'No materials',
    startByAddingMaterial: 'Start by adding a material',
    editCategory: 'Edit Category',
    nameSpanish: 'Name (Spanish)',
    nameEnglish: 'Name (English)',
    descriptionSpanish: 'Description (Spanish)',
    descriptionEnglish: 'Description (English)',
    photoUrl: 'Photo URL',
    photo: 'Photo',
    errorSavingMaterial: 'Error saving material',
    errorDeletingMaterial: 'Error deleting material',
    errorSavingCategory: 'Error saving category',
    errorDeletingCategory: 'Error deleting category',
    categories: 'Categories',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { profile, updateProfile } = useAuth();
  const [language, setLanguageState] = useState<Language>('es');

  useEffect(() => {
    if (profile?.preferred_language) {
      setLanguageState(profile.preferred_language as Language);
    }
  }, [profile]);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    if (profile) {
      await updateProfile({ preferred_language: lang });
    }
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['es']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
